### ISSUE TITLE
'SPI_CLK' was not declared in this scope

### ISSUE THREAD

**Issue by clovett** [VSChina/mbed-iot-devkit-sdk#9] opened 2019-01-09 01:54 UTC
I'm getting some build errors when I use the latest bits using:
```
mbed config --global GCC_ARM_PATH "%GCC_ARM_PATH%"
mbed compile -m AZ3166 -t GCC_ARM --profile release.json
```

errors:
```
[Error] AZ3166SPI.cpp@25,47: 'SPI_CLK' was not declared in this scope
[Error] AZ3166SPI.cpp@25,56: 'SPI_SS' was not declared in this scope
[Warning] AZ3166SPI.cpp@68,16: comparison is always true due to limited range of data type [-Wtype-limits]
[Warning] SystemVariables.h@19,14: 'boardIDHeader' defined but not used [-Wunused-variable]
[Warning] SystemVariables.h@20,14: 'boardAPHeader' defined but not used [-Wunused-variable]
[ERROR] In file included from ./mbed-iot-devkit-sdk/cores/arduino/system/mbed.h:50:0,
                 from .\mbed-iot-devkit-sdk\libraries\SPI\src\AZ3166SPI.h:15,
                 from .\mbed-iot-devkit-sdk\libraries\SPI\src\AZ3166SPI.cpp:12:
./mbed-os/platform/toolchain.h:23:2: warning: #warning toolchain.h has been replaced by mbed_toolchain.h, please update to mbed_toolchain.h [since mbed-os-5.3] [-Wcpp]
 #warning toolchain.h has been replaced by mbed_toolchain.h, please update to mbed_toolchain.h [since mbed-os-5.3]
```

**Comment by lovettchris** [comment] 2019-02-06 19:12
The fix for this appears to be adding the following mbed_app.json settings:
```
{
    "macros": [
        "OLED_I2C_PORT=MICO_I2C_1", 
        "LPS25HB_I2C_PORT=MICO_I2C_1",
        "MBEDTLS_SHA1_C", 
        "MBEDTLS_MD5_C", 
        "MBEDTLS_SSL_PROTO_TLS1_1",
        "LWIP_TIMEVAL_PRIVATE=0",
        "DONT_USE_UPLOADTOBLOB",
        "USE_PROV_MODULE",
        "HSM_TYPE_X509",
        "HSM_TYPE_SYMM_KEY",
        "USE_MBED_TLS",
        "MBED_HEAP_STATS_ENABLED=1",
        "MBED_STACK_STATS_ENABLED=1",
        "NDEBUG=1"
    ],

    "config": {
    }
}
```

**Comment by ArthurMa1978** [comment] 2019-02-11 03:12
> The fix for this appears to be adding the following mbed_app.json settings:
> {
>     "macros": [
>         "OLED_I2C_PORT=MICO_I2C_1", 
>         "LPS25HB_I2C_PORT=MICO_I2C_1",
>         "MBEDTLS_SHA1_C", 
>         "MBEDTLS_MD5_C", 
>         "MBEDTLS_SSL_PROTO_TLS1_1",
>         "LWIP_TIMEVAL_PRIVATE=0",
>         "DONT_USE_UPLOADTOBLOB",
>         "USE_PROV_MODULE",
>         "HSM_TYPE_X509",
>         "HSM_TYPE_SYMM_KEY",
>         "USE_MBED_TLS",
>         "MBED_HEAP_STATS_ENABLED=1",
>         "MBED_STACK_STATS_ENABLED=1",
>         "NDEBUG=1"
>     ],
> 
>     "config": {
>     }
> }

this issue caused by we renamed the pins for external SPI in the [mbed-os0(https://github.com/VSChina/mbed-os) repo, so please update the mbed-os.lib in your app to point to the latest version of mbed-os.

**Closed** 2019-03-15 09:13 UTC
